In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df=pd.read_excel(r"C:\Users\DELL\Downloads\Financial_Sample.xlsx")

In [17]:
df.head(5)

,Segment,Country,Product,Discount Band,Units Sold,Manufacturing Price,Sale Price,Gross Sales,Discounts,Sales,COGS,Profit,Date,Month Number,Month Name,Year
0,NaN,Canada,Carretera,NaN,1618.5,3,20.0,32370.0,0.0,32370.0,16185.0,16185.0,2014-01-01,1,January,2014
1,NaN,Germany,Carretera,NaN,1321.0,3,20.0,26420.0,0.0,26420.0,13210.0,13210.0,2014-01-01,1,January,2014
2,NaN,France,Carretera,NaN,2178.0,3,15.0,32670.0,0.0,32670.0,21780.0,10890.0,2014-06-01,6,June,2014
3,NaN,Germany,Carretera,NaN,888.0,3,15.0,13320.0,0.0,13320.0,8880.0,4440.0,2014-06-01,6,June,2014
4,NaN,Mexico,Carretera,NaN,2470.0,3,15.0,37050.0,0.0,37050.0,24700.0,12350.0,2014-06-01,6,June,2014

In [4]:
newdf=df.copy(2)

In [5]:
newdf.head(3)

,Segment,Country,Product,Discount Band,Units Sold,Manufacturing Price,Sale Price,Gross Sales,Discounts,Sales,COGS,Profit,Date,Month Number,Month Name,Year
0,Government,Canada,Carretera,NaN,1618.5,3,20.0,32370.0,0.0,32370.0,16185.0,16185.0,2014-01-01,1,January,2014
1,Government,Germany,Carretera,NaN,1321.0,3,20.0,26420.0,0.0,26420.0,13210.0,13210.0,2014-01-01,1,January,2014
2,Midmarket,France,Carretera,NaN,2178.0,3,15.0,32670.0,0.0,32670.0,21780.0,10890.0,2014-06-01,6,June,2014

# Ordinal encoding

In [18]:
newdf.Segment.unique()

<ArrowStringArray>
[      'Government',        'Midmarket', 'Channel Partners',
       'Enterprise',   'Small Business',                nan]
Length: 6, dtype: str

In [14]:
dic={"Government":4,"Midmarket":2,"Channel Partners":3,"Enterprise":0,"Small Business":1}

In [19]:
newdf["Segment"]=newdf["Segment"].map(dic)

In [20]:
newdf.head(20)

,Segment,Country,Product,Discount Band,Units Sold,Manufacturing Price,Sale Price,Gross Sales,Discounts,Sales,COGS,Profit,Date,Month Number,Month Name,Year
0,4.0,Canada,Carretera,NaN,1618.5,3,20.0,32370.0,0.0,32370.0,16185.0,16185.0,2014-01-01,1,January,2014
1,4.0,Germany,Carretera,NaN,1321.0,3,20.0,26420.0,0.0,26420.0,13210.0,13210.0,2014-01-01,1,January,2014
2,2.0,France,Carretera,NaN,2178.0,3,15.0,32670.0,0.0,32670.0,21780.0,10890.0,2014-06-01,6,June,2014
3,2.0,Germany,Carretera,NaN,888.0,3,15.0,13320.0,0.0,13320.0,8880.0,4440.0,2014-06-01,6,June,2014
4,2.0,Mexico,Carretera,NaN,2470.0,3,15.0,37050.0,0.0,37050.0,24700.0,12350.0,2014-06-01,6,June,2014
5,4.0,Germany,Carretera,NaN,1513.0,3,350.0,529550.0,0.0,529550.0,393380.0,136170.0,2014-12-01,12,December,2014
6,2.0,Germany,Montana,NaN,921.0,5,15.0,13815.0,0.0,13815.0,9210.0,4605.0,2014-03-01,3,March,2014
7,3.0,Canada,Montana,NaN,2518.0,5,12.0,30216.0,0.0,30216.0,7554.0,22662.0,2014-06-01,6,June,2014
8,4.0,France,Montana,NaN,1899.0,5,20.0,37980.0,0.0,37980.0,18990.0,18990.0,2014-06-01,6,June,2014
9,3.0,Germany,Montana,NaN,1545.0,5,12.0,18540.0,0.0,18540.0,4635.0,13905.0,2014-06-01,6,June,2014
10,2.0,Mexico,Montana,NaN,2470.0,5,15.0,37050.0,0.0,37050.0,24700.0,12350.0,2014-06-01,6,June,2014
11,0.0,Canada,Montana,NaN,2665.5,5,125.0,333187.5,0.0,333187.5,319860.0,13327.5,2014-07-01,7,July,2014
12,1.0,Mexico,Montana,NaN,958.0,5,300.0,287400.0,0.0,287400.0,239500.0,47900.0,2014-08-01,8,August,2014
13,4.0,Germany,Montana,NaN,2146.0,5,7.0,15022.0,0.0,15022.0,10730.0,4292.0,2014-09-01,9,September,2014
14,0.0,Canada,Montana,NaN,345.0,5,125.0,43125.0,0.0,43125.0,41400.0,1725.0,2013-10-01,10,October,2013
15,2.0,United States of America,Montana,NaN,615.0,5,15.0,9225.0,0.0,9225.0,6150.0,3075.0,2014-12-01,12,December,2014
16,4.0,Canada,Paseo,NaN,292.0,10,20.0,5840.0,0.0,5840.0,2920.0,2920.0,2014-02-01,2,February,2014
17,2.0,Mexico,Paseo,NaN,974.0,10,15.0,14610.0,0.0,14610.0,9740.0,4870.0,2014-02-01,2,February,2014
18,3.0,Canada,Paseo,NaN,2518.0,10,12.0,30216.0,0.0,30216.0,7554.0,22662.0,2014-06-01,6,June,2014
19,4.0,Germany,Paseo,NaN,1006.0,10,350.0,352100.0,0.0,352100.0,261560.0,90540.0,2014-06-01,6,June,2014

In [21]:
newdf.Country.unique()

<ArrowStringArray>
['Canada', 'Germany', 'France', 'Mexico', 'United States of America', nan]
Length: 6, dtype: str

In [22]:
from sklearn.preprocessing import OrdinalEncoder

In [23]:
oe=OrdinalEncoder(categories=["United States of America","Germany","France","Mexico",'Canada'])

In [25]:
newdf['Country']=newdf['Country']=oe.fit_transform(newdf[['Country']])

ValueError: Shape mismatch: if categories is an array, it has to be of shape (n_features,).